apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector: 
     app: schedular
  ports:
   - protocol: TCP
     port: {{ .Values.service.workerbeat.port }}
     targetPort: {{ .Values.service.workerbeat.targetport }}
  type: ClusterIP

