release:
 name: tenant1
storageclassname: tenant1-ebs-sc
namespace:
 name: tenant1
pods:
 pod1:
  name: tenant1-akashic-bi-db
  restartPolicy: Always
 pod2: 
  name: tenant1-akashic-bi-superset
  restartPolicy: Always
supersetContainer:
  name: superset-app
  image: 802160436285.dkr.ecr.us-west-1.amazonaws.com/akashicmt:superset0.4
  port: 8088
  imagepullPolicy: IfNotPresent
superset_initcontainer:
  name: superset-init
  image: 802160436285.dkr.ecr.us-west-1.amazonaws.com/akashicmt:superset0.4
  imagepullPolicy: IfNotPresent
databaseContainer:
  name: superset-db
  image: postgres:15
  imagepullPolicy: IfNotPresent
redisContainer:
  name: superset-cache
  image: redis:7
  imagepullPolicy: IfNotPresent
pvc:
  redis:
    storageClassName: tenant1-ebs-sc
    name: tenant1-redis-pvc
    storage: 5Gi
  database:
    storageClassName: tenant1-ebs-sc
    name: tenant1-database-pvc
    storage: 15Gi
  superset:
    storageClassName: tenant1-ebs-sc
    name: tenant1-superset-pvc
    storage: 5Gi
configMapdata:
  superset:
    pythonpath: /app/pythonpath:/app/docker/pythonpath_dev
    supersetenv: production
    cypressconfig: false
    mapboxapikey: ''
ecrsecretname: tenant1-awsecr-cred 
secretcredname: tenant1-db-app-credentials 
configmapname: tenant1-db-app-config 
file1configmap: tenant1-mnt-config
file2configmap: tenant1-db-mnt-config
file3configmap: tenant1-mnt1-config
service:
  database:
    port: 5432
    targetport: 5432
  redis:
    port: 6379
    targetport: 6379