apiVersion: v1
kind: Service
metadata:
  labels:
    app: superset
  name: service
  namespace: {{ .Values.namespace.name | quote }}
spec:
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  selector:
    app: superset
  type: NodePort

