apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-redis-service
spec:
  selector: 
     app: database-redis
  ports:
   - name: db-port
     protocol: TCP
     port: {{ .Values.service.database.port }}
     targetPort: {{ .Values.service.database.targetport }}
   - name: redis-port
     protocol: TCP
     port: {{ .Values.service.redis.port }}
     targetPort: {{ .Values.service.redis.targetport }}
  type: ClusterIP