apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector: 
     app: database-engine
  ports:
   - protocol: TCP
     port: {{ .Values.service.worker.port }}
     targetPort: {{ .Values.service.worker.targetport }}
  type: ClusterIP
